-- Subcategorías dentro de las secciones existentes (lentes, pestañas, accesorios).
-- Ya aplicada en el proyecto Marao; se guarda aquí para reproducirla.
-- La administradora las crea y ordena desde el panel; la tienda las pinta sola.

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null check (length(btrim(nombre)) > 0),
  seccion text not null check (seccion in ('lente', 'pestana', 'accesorio')),
  orden integer not null default 0,
  creado_en timestamptz not null default now()
);

-- Sin duplicados dentro de una sección, ignorando mayúsculas y espacios.
create unique index if not exists categorias_seccion_nombre_key
  on public.categorias (seccion, lower(btrim(nombre)));

alter table public.categorias enable row level security;

drop policy if exists "Public can read categories" on public.categorias;
drop policy if exists "Admin can insert categories" on public.categorias;
drop policy if exists "Admin can update categories" on public.categorias;
drop policy if exists "Admin can delete categories" on public.categorias;

create policy "Public can read categories"
on public.categorias for select
to anon, authenticated
using (true);

create policy "Admin can insert categories"
on public.categorias for insert
to authenticated
with check (auth.jwt() ->> 'email' = 'admin@marao.com');

create policy "Admin can update categories"
on public.categorias for update
to authenticated
using (auth.jwt() ->> 'email' = 'admin@marao.com')
with check (auth.jwt() ->> 'email' = 'admin@marao.com');

create policy "Admin can delete categories"
on public.categorias for delete
to authenticated
using (auth.jwt() ->> 'email' = 'admin@marao.com');

-- Al eliminar una subcategoría, sus productos se quedan sin ella.
alter table public.productos
  add column if not exists categoria_id bigint
  references public.categorias (id) on delete set null;

create index if not exists productos_categoria_id_idx
  on public.productos (categoria_id);
