-- Subcategorías dentro de las secciones existentes (lentes, pestañas, accesorios).
-- Ya aplicada en el proyecto Marao; se guarda aquí para reproducirla.
-- La administradora las crea y ordena desde el panel; la tienda las pinta sola.

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null check (length(btrim(nombre)) > 0),
  seccion text not null check (seccion in ('lente', 'pestana', 'accesorio')),
  orden integer not null default 0,
  creado_en timestamptz not null default now()
);

-- Sin duplicados dentro de una sección, ignorando mayúsculas y espacios.
create unique index if not exists categorias_seccion_nombre_key
  on public.categorias (seccion, lower(btrim(nombre)));

alter table public.categorias enable row level security;

drop policy if exists "Public can read categories" on public.categorias;
drop policy if exists "Admin can insert categories" on public.categorias;
drop policy if exists "Admin can update categories" on public.categorias;
drop policy if exists "Admin can delete categories" on public.categorias;

create policy "Public can read categories"
on public.categorias for select
to anon, authenticated
using (true);

create policy "Admin can insert categories"
on public.categorias for insert
to authenticated
with check (public.es_admin());

create policy "Admin can update categories"
on public.categorias for update
to authenticated
using (public.es_admin())
with check (public.es_admin());

create policy "Admin can delete categories"
on public.categorias for delete
to authenticated
using (public.es_admin());

-- Al eliminar una subcategoría, sus productos se quedan sin ella.
alter table public.productos
  add column if not exists categoria_id bigint
  references public.categorias (id) on delete set null;

create index if not exists productos_categoria_id_idx
  on public.productos (categoria_id);

-- Categorías de Lentes: pupila reducida, pupila estándar y cosplay Halloween.
-- Cada lente toma la equivalente a su `tipo`, que se conserva por
-- compatibilidad (el código anterior filtraba por él).
update public.categorias
set nombre = 'Cosplay Halloween', orden = 3
where seccion = 'lente' and lower(btrim(nombre)) = 'halloween';

insert into public.categorias (nombre, seccion, orden)
select v.nombre, 'lente', v.orden
from (values ('Pupila reducida', 1), ('Pupila estándar', 2), ('Cosplay Halloween', 3)) as v(nombre, orden)
where not exists (
  select 1 from public.categorias c
  where c.seccion = 'lente' and lower(btrim(c.nombre)) = lower(v.nombre)
);

update public.productos p
set categoria_id = c.id
from public.categorias c
where p.categoria_id is null
  and c.seccion = 'lente'
  and c.nombre = case p.tipo
    when 'reducida' then 'Pupila reducida'
    when 'estandar' then 'Pupila estándar'
    when 'cosplay' then 'Cosplay Halloween'
  end;
