import { IMG_PATH, PRECIO_LENTES } from "./constantes.js";

/**
 * Lentes de contacto para cosplay.
 *
 * Fuente distinta a la del catálogo cosmético: las referencias llegaron por
 * WhatsApp del proveedor (ver `lentes-cosplay/lentes-cosplay.md`), no del
 * documento del catálogo. Por eso viven en su propio archivo y no en
 * `lentes.js`, que se regenera a partir de ese documento.
 *
 * Diferencias con un lente cosmético:
 * - `tipo: "cosplay"` — no se clasifican por pupila reducida/estándar, así que
 *   quedan fuera de ese filtro y solo aparecen con la pupila en "todas".
 * - `categoria` — agrupación temática sugerida al catalogarlos (Anime, Terror,
 *   Fantasía...), no viene del proveedor.
 */

const IMG_COSPLAY = IMG_PATH + "lentes/cosplay/";

export const lentesCosplay = [
  {
    id: 2001,
    nombre: "BLANCO CIEGO",
    alias: [],
    desc: "Lente de contacto cosplay blanco ciego. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Blancos / terror",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "01-blanco-ciego.jpeg",
    imagenes: [IMG_COSPLAY + "01-blanco-ciego.jpeg"]
  },
  {
    id: 2002,
    nombre: "BLANCO NORMAL",
    alias: [],
    desc: "Lente de contacto cosplay blanco normal. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Blancos / terror",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "02-blanco-normal.jpeg",
    imagenes: [IMG_COSPLAY + "02-blanco-normal.jpeg"]
  },
  {
    id: 2003,
    nombre: "BLANCO MALLA",
    alias: [],
    desc: "Lente de contacto cosplay blanco malla. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Blancos / terror",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "03-blanco-malla.jpeg",
    imagenes: [IMG_COSPLAY + "03-blanco-malla.jpeg"]
  },
  {
    id: 2004,
    nombre: "BLANCO CON BORDE NEGRO",
    alias: [],
    desc: "Lente de contacto cosplay blanco con borde negro. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Blancos / terror",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "04-blanco-con-borde-negro.jpeg",
    imagenes: [IMG_COSPLAY + "04-blanco-con-borde-negro.jpeg"]
  },
  {
    id: 2005,
    nombre: "SHARINGAN",
    alias: [],
    desc: "Lente de contacto cosplay sharingan. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Anime - Naruto",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "05-sharingan.jpeg",
    imagenes: [IMG_COSPLAY + "05-sharingan.jpeg"]
  },
  {
    id: 2006,
    nombre: "ROJO CON BORDE",
    alias: [],
    desc: "Lente de contacto cosplay rojo con borde. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Rojos",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "06-rojo-con-borde.jpeg",
    imagenes: [IMG_COSPLAY + "06-rojo-con-borde.jpeg"]
  },
  {
    id: 2007,
    nombre: "ROJO",
    alias: [],
    desc: "Lente de contacto cosplay rojo. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Rojos",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "07-rojo.jpeg",
    imagenes: [IMG_COSPLAY + "07-rojo.jpeg"]
  },
  {
    id: 2008,
    nombre: "GREY CRACK",
    alias: [],
    desc: "Lente de contacto cosplay grey crack. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Fantasia",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "08-grey-crack.jpeg",
    imagenes: [IMG_COSPLAY + "08-grey-crack.jpeg"]
  },
  {
    id: 2009,
    nombre: "RED VIOLET",
    alias: [],
    desc: "Lente de contacto cosplay red violet. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Rojos",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "09-red-violet.jpeg",
    imagenes: [IMG_COSPLAY + "09-red-violet.jpeg"]
  },
  {
    id: 2010,
    nombre: "STITCHED MUMMY",
    alias: [],
    desc: "Lente de contacto cosplay stitched mummy. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Terror / Halloween",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "10-stitched-mummy.jpeg",
    imagenes: [IMG_COSPLAY + "10-stitched-mummy.jpeg"]
  },
  {
    id: 2011,
    nombre: "GREEN MASON",
    alias: [],
    desc: "Lente de contacto cosplay green mason. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Fantasia",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "11-green-mason.jpeg",
    imagenes: [IMG_COSPLAY + "11-green-mason.jpeg"]
  },
  {
    id: 2012,
    nombre: "KITAGAWA PINK",
    alias: [],
    desc: "Lente de contacto cosplay kitagawa pink. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Anime - Marin Kitagawa",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "12-kitagawa-pink.jpeg",
    imagenes: [IMG_COSPLAY + "12-kitagawa-pink.jpeg"]
  },
  {
    id: 2013,
    nombre: "WHITE SLIT",
    alias: [],
    desc: "Lente de contacto cosplay white slit. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Terror / pupila felina",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "13-white-slit.jpeg",
    imagenes: [IMG_COSPLAY + "13-white-slit.jpeg"]
  },
  {
    id: 2014,
    nombre: "NEZUKO DEMON",
    alias: [],
    desc: "Lente de contacto cosplay nezuko demon. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Anime - Demon Slayer",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "14-nezuko-demon.jpeg",
    imagenes: [IMG_COSPLAY + "14-nezuko-demon.jpeg"]
  },
  {
    id: 2015,
    nombre: "PURPLE",
    alias: [],
    desc: "Lente de contacto cosplay purple. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Fantasia",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "15-purple.jpeg",
    imagenes: [IMG_COSPLAY + "15-purple.jpeg"]
  },
  {
    id: 2016,
    nombre: "RUI",
    alias: [],
    desc: "Lente de contacto cosplay rui. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Anime - Demon Slayer",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "16-rui.jpeg",
    imagenes: [IMG_COSPLAY + "16-rui.jpeg"]
  },
  {
    id: 2017,
    nombre: "TANJIRO KAMADO",
    alias: [],
    desc: "Lente de contacto cosplay tanjiro kamado. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Anime - Demon Slayer",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "17-tanjiro-kamado.jpeg",
    imagenes: [IMG_COSPLAY + "17-tanjiro-kamado.jpeg"]
  },
  {
    id: 2018,
    nombre: "NEBULA VDB 12 YELLOW",
    alias: [],
    desc: "Lente de contacto cosplay nebula vdb 12 yellow. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Fantasia",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "18-nebula-vdb-12-yellow.jpeg",
    imagenes: [IMG_COSPLAY + "18-nebula-vdb-12-yellow.jpeg"]
  },
  {
    id: 2019,
    nombre: "ARCOIRIS",
    alias: [],
    desc: "Lente de contacto cosplay arcoiris. Diseño de fantasía para caracterización y disfraces.",
    precio: PRECIO_LENTES,
    tipo: "cosplay",
    color: "cosplay",
    categoria: "Fantasia",
    cobertura: null,
    borde: null,
    efecto: null,
    promocion: false,
    presentaciones: [],
    img: IMG_COSPLAY + "19-arcoiris.jpeg",
    imagenes: [IMG_COSPLAY + "19-arcoiris.jpeg"]
  }
];
